const fs = require('fs');
const path = require('path');
const minify = require('html-minifier').minify;

const out_dir = path.join(__dirname, "..", "email");
if (!fs.existsSync(out_dir)) fs.mkdirSync();

const width = 600;

hexo.on('exit', ()=>{
    const posts = hexo.locals.get("posts");
    
    posts.forEach(post=>{

        let content = post.content.replace(/src=['"]\//g, `src="${hexo.config.url}/`);
        
        content =
`<!DOCTYPE html>
<html>
<head>
    <title>${post.title} - ${post.excerpt}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <style type='text/css'>
        @import url("https://fonts.googleapis.com/css?family=Aclonica|Poppins:300,400,500,600&display=swap");
        body {
            font-family: "Poppins", sans-serif;
            padding: 0;
            margin: 0;
            font-size: 14px;
            color: #888;
        }
        img {
            width:100%;
            height:auto;
        }
        #weblink {
            text-align:center;
            font-size:12px;
        }
        #unsublink {
            font-size:10px;
        }
        .websitelink {
            font-size: 18px;
            text-align:center;
        }
        h1,h2,h3,h4,h5,h6 {
            font-family: "Aclonica", sans-serif;
            color:black;
        }
        .container${width}{
            width: ${width}px;
        }
    </style>
</head>
<body>
    <center>
    <!--[if gte mso 9]><table width="${width}" cellpadding="0" cellspacing="0"><tr><td><![endif]-->
    <table class="container${width}" width="100%" style="max-width:${width}px;margin: 0 auto;" cellpadding="0" cellspacing="0" border="0">
        <tr>
        <td width="100%" style="text-align:left;">
            <div id="weblink">
                <webversion>web version of email</webversion>
            </div>
            <hr />
            <br />
            <div id='content'>
                <div class='websitelink'>
                    <a href='${post.permalink}'>View This Post On Website</a>
                </div>
                ${content}
                <div class='websitelink'>
                    <a href='${post.permalink}/#disqus_thread'>View Comments</a>
                </div>
            </div>
            <br />
            <hr />
            <div id="unsublink">
                <unsubscribe>Click here to unsubscribe from the newsletter.</unsubscribe>
            </div>

        </td>
        </tr>
    </table>
    <!--[if gte mso 9]></td></tr></table><![endif]-->
    </center>
</body>
</html>`;

        content = minify(content, {
            includeAutoGeneratedTags: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            sortClassName: true,
            useShortDoctype: true,
            collapseWhitespace: true,
            minifyCSS: true
        });

        fs.writeFileSync(path.join(__dirname, "..", "email", `${path.basename(post.source)}.html`), content);
    
    });

});